//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIAUTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignDetails
    {
        public int ID { get; set; }
        public int CampaignTypeId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.Guid Created_By { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<System.Guid> Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string HowItWorks_Text { get; set; }
        public string ViewSampleSite_Text { get; set; }
        public string LaunchACampaign_Text { get; set; }
        public string ViewSampleSite_Url { get; set; }
        public string LaunchACampaign_Url { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<int> BusinessLine { get; set; }
        public Nullable<int> Campaign_Group_id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string CallScript { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> MicroPortalID { get; set; }
        public string Content { get; set; }
        public string Banner { get; set; }
        public string UserViewType { get; set; }
        public bool IsSubRegion { get; set; }
        public bool isNewMicrosite { get; set; }
    }
}
