//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIAUTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIALSHARINGDETAILS
    {
        public System.Guid ID { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public Nullable<int> CAMPAIGN_ID { get; set; }
        public string POST_ID { get; set; }
        public string POST_NAME { get; set; }
        public string POST_CONTENT { get; set; }
        public Nullable<System.DateTime> POST_DATE { get; set; }
        public string POST_TYPE { get; set; }
        public Nullable<int> POST_SHARE_COUNT { get; set; }
        public Nullable<int> POST_LIKE_COUNT { get; set; }
        public Nullable<int> POST_COMMENT_COUNT { get; set; }
        public Nullable<bool> ISPUBLISHED { get; set; }
        public string SOCIALID { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
        public string CMMPostType { get; set; }
        public string PostTag { get; set; }
        public string TIMEZONE { get; set; }
        public Nullable<System.DateTime> SCHEDULEUSERDATE { get; set; }
        public Nullable<System.DateTime> SCHEDULEPOSTDATE { get; set; }
        public Nullable<System.Guid> ParentPostId { get; set; }
        public string Quarter { get; set; }
        public string pageid { get; set; }
        public string FormatType { get; set; }
        public string Imagepath { get; set; }
        public string NameTitle { get; set; }
        public string Link { get; set; }
        public string FBDescription { get; set; }
        public string FBCaption { get; set; }
        public Nullable<bool> AllowCPImageChange { get; set; }
        public bool IsCreatedforCMM { get; set; }
    }
}
