//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIAUTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERACCESSTOKENASSOC
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> USER_ID { get; set; }
        public string CONSUMERKEY { get; set; }
        public string CONSUMERSECRET { get; set; }
        public string ACCESSTOKEN { get; set; }
        public string TOKENSECRET { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public string SOCIAL_TYPE { get; set; }
        public string SocialId { get; set; }
        public string SocialAcctName { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public string associatedPageId { get; set; }
        public string PageName { get; set; }
        public string pageaccesstoken { get; set; }
        public Nullable<int> DefaultCampaignID { get; set; }
        public bool IsCorporateCMMAccount { get; set; }
    }
}
